# Generated by Django 3.1.3 on 2020-11-02 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LocationVisitHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('category', models.CharField(choices=[('Residence', 'Residence'), ('Workplace', 'Workplace'), ('Visit', 'Visit')], default='Visit', max_length=10)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.case')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
            ],
        ),
    ]
