# Generated by Django 3.1.2 on 2020-11-02 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_locationvisithistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationvisithistory',
            name='patient_id',
        ),
    ]
