# Generated by Django 3.1.2 on 2020-11-02 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_auto_20201102_0810'),
        ('location', '0003_remove_locationvisithistory_patient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationvisithistory',
            old_name='location_id',
            new_name='location',
        ),
        migrations.AddField(
            model_name='locationvisithistory',
            name='case',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='case.case'),
            preserve_default=False,
        ),
    ]
