# Generated by Django 3.1.2 on 2020-11-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20201102_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='local_or_imported',
            field=models.CharField(choices=[('Local', 'Local'), ('Imported', 'Imported')], default='Local', max_length=10),
        ),
    ]
