# Generated by Django 3.1.2 on 2020-11-02 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_auto_20201102_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='virus_id',
            new_name='virus',
        ),
    ]
